import { Project } from '../types';

export const PRESET_TEMPLATES: Project[] = [
  {
    id: 'cyberpunk-neon',
    title: 'Cyberpunk Neon Emblem',
    aspectRatio: '16:9',
    fps: 60,
    duration: 5.0,
    backgroundColor: '#090a10',
    backgroundGradient: 'radial-gradient(circle at center, #181b2e 0%, #06070a 100%)',
    bgPattern: 'grid',
    audioTrack: {
      id: 'cyber-beat',
      title: 'Cyber Synthwave',
      duration: 5.0,
      volume: 0.8,
      syntheticType: 'cyber',
    },
    transitions: [
      { id: 't1', type: 'glitch', time: 0, duration: 0.5 },
      { id: 't2', type: 'rgbSplit', time: 4.5, duration: 0.5 },
    ],
    layers: [
      {
        id: 'bg-glow-ring',
        name: 'Glow Ring Pulse',
        type: 'shape',
        shapeKind: 'ring',
        innerRadius: 0.7,
        visible: true,
        locked: false,
        zIndex: 1,
        soundEffect: 'whoosh',
        keyframes: [
          {
            id: 'k1',
            time: 0,
            x: 0,
            y: 0,
            scaleX: 0.2,
            scaleY: 0.2,
            rotation: -180,
            opacity: 0,
            fill: '#00f0ff',
            stroke: '#ff007f',
            strokeWidth: 4,
            trimStart: 0,
            trimEnd: 0,
            blur: 15,
            glowColor: '#00f0ff',
            glowRadius: 25,
            easing: 'elastic',
          },
          {
            id: 'k2',
            time: 1.2,
            x: 0,
            y: 0,
            scaleX: 1.4,
            scaleY: 1.4,
            rotation: 0,
            opacity: 0.85,
            fill: 'rgba(0, 240, 255, 0.1)',
            stroke: '#ff007f',
            strokeWidth: 6,
            trimStart: 0,
            trimEnd: 1,
            blur: 0,
            glowColor: '#00f0ff',
            glowRadius: 30,
            easing: 'easeInOut',
          },
          {
            id: 'k3',
            time: 4.2,
            x: 0,
            y: 0,
            scaleX: 1.5,
            scaleY: 1.5,
            rotation: 45,
            opacity: 0.9,
            fill: 'rgba(0, 240, 255, 0.15)',
            stroke: '#00f0ff',
            strokeWidth: 6,
            trimStart: 0,
            trimEnd: 1,
            blur: 0,
            glowColor: '#ff007f',
            glowRadius: 35,
            easing: 'easeOut',
          },
          {
            id: 'k4',
            time: 5.0,
            x: 0,
            y: 0,
            scaleX: 2.2,
            scaleY: 2.2,
            rotation: 90,
            opacity: 0,
            fill: 'rgba(0, 240, 255, 0)',
            stroke: '#00f0ff',
            strokeWidth: 1,
            trimStart: 0,
            trimEnd: 1,
            blur: 10,
            easing: 'easeIn',
          },
        ],
      },
      {
        id: 'cyber-badge',
        name: 'Hexagonal Cyber Shield',
        type: 'shape',
        shapeKind: 'badge',
        visible: true,
        locked: false,
        zIndex: 2,
        soundEffect: 'stinger',
        keyframes: [
          {
            id: 'k1',
            time: 0.4,
            x: 0,
            y: 0,
            scaleX: 0.1,
            scaleY: 0.1,
            rotation: 90,
            opacity: 0,
            fill: '#0f1322',
            stroke: '#00f0ff',
            strokeWidth: 5,
            trimStart: 0,
            trimEnd: 0,
            blur: 5,
            glowColor: '#00f0ff',
            glowRadius: 20,
            easing: 'bounce',
          },
          {
            id: 'k2',
            time: 1.5,
            x: 0,
            y: 0,
            scaleX: 1,
            scaleY: 1,
            rotation: 0,
            opacity: 1,
            fill: '#0f1322',
            stroke: '#00f0ff',
            strokeWidth: 4,
            trimStart: 0,
            trimEnd: 1,
            blur: 0,
            glowColor: '#00f0ff',
            glowRadius: 20,
            easing: 'easeInOut',
          },
          {
            id: 'k3',
            time: 4.0,
            x: 0,
            y: 0,
            scaleX: 1.05,
            scaleY: 1.05,
            rotation: 0,
            opacity: 1,
            fill: '#151b30',
            stroke: '#ff007f',
            strokeWidth: 4,
            trimStart: 0,
            trimEnd: 1,
            blur: 0,
            glowColor: '#ff007f',
            glowRadius: 25,
            easing: 'linear',
          },
          {
            id: 'k4',
            time: 4.8,
            x: 0,
            y: 0,
            scaleX: 0.05,
            scaleY: 0.05,
            rotation: -90,
            opacity: 0,
            fill: '#0f1322',
            stroke: '#00f0ff',
            strokeWidth: 1,
            trimStart: 0,
            trimEnd: 0,
            blur: 10,
            easing: 'easeIn',
          },
        ],
      },
      {
        id: 'main-title-text',
        name: 'CYBERPUNK Title Text',
        type: 'text',
        text: 'CYBERPUNK',
        fontFamily: 'Montserrat, sans-serif',
        fontSize: 52,
        fontWeight: '900',
        letterSpacing: 8,
        textTransform: 'uppercase',
        visible: true,
        locked: false,
        zIndex: 3,
        soundEffect: 'laser',
        keyframes: [
          {
            id: 'k1',
            time: 1.0,
            x: 0,
            y: -10,
            scaleX: 0.5,
            scaleY: 0.5,
            rotation: 0,
            opacity: 0,
            fill: '#ffffff',
            stroke: '#00f0ff',
            strokeWidth: 2,
            trimStart: 0,
            trimEnd: 1,
            blur: 20,
            glowColor: '#00f0ff',
            glowRadius: 30,
            easing: 'elastic',
          },
          {
            id: 'k2',
            time: 1.8,
            x: 0,
            y: -10,
            scaleX: 1,
            scaleY: 1,
            rotation: 0,
            opacity: 1,
            fill: '#ffffff',
            stroke: '#00f0ff',
            strokeWidth: 1,
            trimStart: 0,
            trimEnd: 1,
            blur: 0,
            glowColor: '#00f0ff',
            glowRadius: 20,
            easing: 'easeInOut',
          },
          {
            id: 'k3',
            time: 4.2,
            x: 0,
            y: -10,
            scaleX: 1.08,
            scaleY: 1.08,
            rotation: 0,
            opacity: 1,
            fill: '#ffffff',
            stroke: '#ff007f',
            strokeWidth: 2,
            trimStart: 0,
            trimEnd: 1,
            blur: 0,
            glowColor: '#ff007f',
            glowRadius: 25,
            easing: 'easeOut',
          },
          {
            id: 'k4',
            time: 4.9,
            x: 0,
            y: -10,
            scaleX: 1.8,
            scaleY: 1.8,
            rotation: 0,
            opacity: 0,
            fill: '#ffffff',
            stroke: '#ff007f',
            strokeWidth: 0,
            trimStart: 0,
            trimEnd: 1,
            blur: 15,
            easing: 'easeIn',
          },
        ],
      },
      {
        id: 'subtitle-text',
        name: 'Sub-Tagline Text',
        type: 'text',
        text: 'MOTION STUDIOS 2026',
        fontFamily: 'Inter, sans-serif',
        fontSize: 16,
        fontWeight: '700',
        letterSpacing: 10,
        textTransform: 'uppercase',
        visible: true,
        locked: false,
        zIndex: 4,
        soundEffect: 'beep',
        keyframes: [
          {
            id: 'k1',
            time: 1.6,
            x: 0,
            y: 45,
            scaleX: 1,
            scaleY: 1,
            rotation: 0,
            opacity: 0,
            fill: '#00f0ff',
            stroke: '#00f0ff',
            strokeWidth: 0,
            trimStart: 0,
            trimEnd: 1,
            blur: 5,
            glowColor: '#00f0ff',
            glowRadius: 10,
            easing: 'easeOut',
          },
          {
            id: 'k2',
            time: 2.2,
            x: 0,
            y: 45,
            scaleX: 1,
            scaleY: 1,
            rotation: 0,
            opacity: 1,
            fill: '#ff007f',
            stroke: '#ff007f',
            strokeWidth: 0,
            trimStart: 0,
            trimEnd: 1,
            blur: 0,
            glowColor: '#ff007f',
            glowRadius: 15,
            easing: 'linear',
          },
          {
            id: 'k3',
            time: 4.2,
            x: 0,
            y: 45,
            scaleX: 1,
            scaleY: 1,
            rotation: 0,
            opacity: 1,
            fill: '#00f0ff',
            stroke: '#00f0ff',
            strokeWidth: 0,
            trimStart: 0,
            trimEnd: 1,
            blur: 0,
            glowColor: '#00f0ff',
            glowRadius: 15,
            easing: 'easeOut',
          },
          {
            id: 'k4',
            time: 4.8,
            x: 0,
            y: 45,
            scaleX: 1,
            scaleY: 1,
            rotation: 0,
            opacity: 0,
            fill: '#00f0ff',
            stroke: '#00f0ff',
            strokeWidth: 0,
            trimStart: 0,
            trimEnd: 1,
            blur: 10,
            easing: 'easeIn',
          },
        ],
      },
    ],
  },
  {
    id: 'minimal-tech',
    title: 'Minimalist Tech Reveal',
    aspectRatio: '16:9',
    fps: 60,
    duration: 4.5,
    backgroundColor: '#0a0d14',
    backgroundGradient: 'linear-gradient(135deg, #0e1320 0%, #05070a 100%)',
    bgPattern: 'dots',
    audioTrack: {
      id: 'chill-beat',
      title: 'Modern Chill Tech',
      duration: 4.5,
      volume: 0.7,
      syntheticType: 'chill',
    },
    transitions: [
      { id: 't1', type: 'zoomBlur', time: 0, duration: 0.4 },
      { id: 't2', type: 'fade', time: 4.0, duration: 0.5 },
    ],
    layers: [
      {
        id: 'center-circle',
        name: 'Expanding Center Circle',
        type: 'shape',
        shapeKind: 'circle',
        visible: true,
        locked: false,
        zIndex: 1,
        soundEffect: 'pop',
        keyframes: [
          {
            id: 'k1',
            time: 0,
            x: 0,
            y: 0,
            scaleX: 0,
            scaleY: 0,
            rotation: 0,
            opacity: 0,
            fill: '#6366f1',
            stroke: '#a5b4fc',
            strokeWidth: 4,
            trimStart: 0,
            trimEnd: 0,
            blur: 0,
            glowColor: '#6366f1',
            glowRadius: 20,
            easing: 'elastic',
          },
          {
            id: 'k2',
            time: 1.0,
            x: 0,
            y: 0,
            scaleX: 1,
            scaleY: 1,
            rotation: 0,
            opacity: 1,
            fill: 'rgba(99, 102, 241, 0.15)',
            stroke: '#a5b4fc',
            strokeWidth: 3,
            trimStart: 0,
            trimEnd: 1,
            blur: 0,
            glowColor: '#6366f1',
            glowRadius: 20,
            easing: 'easeInOut',
          },
          {
            id: 'k3',
            time: 3.8,
            x: 0,
            y: 0,
            scaleX: 1.1,
            scaleY: 1.1,
            rotation: 0,
            opacity: 1,
            fill: 'rgba(99, 102, 241, 0.2)',
            stroke: '#6366f1',
            strokeWidth: 3,
            trimStart: 0,
            trimEnd: 1,
            blur: 0,
            glowColor: '#a5b4fc',
            glowRadius: 25,
            easing: 'easeOut',
          },
          {
            id: 'k4',
            time: 4.5,
            x: 0,
            y: 0,
            scaleX: 3,
            scaleY: 3,
            rotation: 0,
            opacity: 0,
            fill: 'rgba(99, 102, 241, 0)',
            stroke: '#6366f1',
            strokeWidth: 1,
            trimStart: 0,
            trimEnd: 1,
            blur: 10,
            easing: 'easeIn',
          },
        ],
      },
      {
        id: 'brand-title',
        name: 'Brand Name Text',
        type: 'text',
        text: 'NEXUS',
        fontFamily: 'Outfit, sans-serif',
        fontSize: 64,
        fontWeight: '800',
        letterSpacing: 12,
        visible: true,
        locked: false,
        zIndex: 2,
        soundEffect: 'riser',
        keyframes: [
          {
            id: 'k1',
            time: 0.5,
            x: 0,
            y: 20,
            scaleX: 0.8,
            scaleY: 0.8,
            rotation: 0,
            opacity: 0,
            fill: '#ffffff',
            stroke: '#6366f1',
            strokeWidth: 0,
            trimStart: 0,
            trimEnd: 1,
            blur: 10,
            glowColor: '#a5b4fc',
            glowRadius: 20,
            easing: 'bounce',
          },
          {
            id: 'k2',
            time: 1.4,
            x: 0,
            y: 0,
            scaleX: 1,
            scaleY: 1,
            rotation: 0,
            opacity: 1,
            fill: '#ffffff',
            stroke: '#6366f1',
            strokeWidth: 0,
            trimStart: 0,
            trimEnd: 1,
            blur: 0,
            glowColor: '#a5b4fc',
            glowRadius: 15,
            easing: 'easeInOut',
          },
          {
            id: 'k3',
            time: 3.8,
            x: 0,
            y: -5,
            scaleX: 1.05,
            scaleY: 1.05,
            rotation: 0,
            opacity: 1,
            fill: '#ffffff',
            stroke: '#6366f1',
            strokeWidth: 0,
            trimStart: 0,
            trimEnd: 1,
            blur: 0,
            glowColor: '#6366f1',
            glowRadius: 15,
            easing: 'easeOut',
          },
          {
            id: 'k4',
            time: 4.5,
            x: 0,
            y: -30,
            scaleX: 1.2,
            scaleY: 1.2,
            rotation: 0,
            opacity: 0,
            fill: '#ffffff',
            stroke: '#6366f1',
            strokeWidth: 0,
            trimStart: 0,
            trimEnd: 1,
            blur: 15,
            easing: 'easeIn',
          },
        ],
      },
    ],
  },
  {
    id: 'gaming-burst',
    title: 'Gaming Energy Burst',
    aspectRatio: '16:9',
    fps: 60,
    duration: 5.0,
    backgroundColor: '#0c0714',
    backgroundGradient: 'radial-gradient(circle at center, #230f38 0%, #08030d 100%)',
    bgPattern: 'hexagons',
    audioTrack: {
      id: 'energetic-beat',
      title: 'Heavy Bass EDM',
      duration: 5.0,
      volume: 0.9,
      syntheticType: 'energetic',
    },
    transitions: [
      { id: 't1', type: 'flash', time: 0, duration: 0.3 },
      { id: 't2', type: 'glitch', time: 4.5, duration: 0.5 },
    ],
    layers: [
      {
        id: 'star-burst',
        name: 'Energy Rays Burst',
        type: 'shape',
        shapeKind: 'burst',
        visible: true,
        locked: false,
        zIndex: 1,
        soundEffect: 'bassDrop',
        keyframes: [
          {
            id: 'k1',
            time: 0.2,
            x: 0,
            y: 0,
            scaleX: 0.1,
            scaleY: 0.1,
            rotation: 0,
            opacity: 0,
            fill: 'none',
            stroke: '#e11d48',
            strokeWidth: 4,
            trimStart: 0,
            trimEnd: 0,
            blur: 0,
            glowColor: '#f43f5e',
            glowRadius: 20,
            easing: 'elastic',
          },
          {
            id: 'k2',
            time: 1.2,
            x: 0,
            y: 0,
            scaleX: 1.8,
            scaleY: 1.8,
            rotation: 120,
            opacity: 1,
            fill: 'none',
            stroke: '#fb7185',
            strokeWidth: 5,
            trimStart: 0,
            trimEnd: 1,
            blur: 0,
            glowColor: '#fb7185',
            glowRadius: 30,
            easing: 'easeInOut',
          },
          {
            id: 'k3',
            time: 4.0,
            x: 0,
            y: 0,
            scaleX: 2.2,
            scaleY: 2.2,
            rotation: 240,
            opacity: 0.8,
            fill: 'none',
            stroke: '#e11d48',
            strokeWidth: 3,
            trimStart: 0,
            trimEnd: 1,
            blur: 0,
            glowColor: '#e11d48',
            glowRadius: 25,
            easing: 'linear',
          },
          {
            id: 'k4',
            time: 5.0,
            x: 0,
            y: 0,
            scaleX: 3.5,
            scaleY: 3.5,
            rotation: 360,
            opacity: 0,
            fill: 'none',
            stroke: '#e11d48',
            strokeWidth: 1,
            trimStart: 0,
            trimEnd: 1,
            blur: 15,
            easing: 'easeIn',
          },
        ],
      },
      {
        id: 'gaming-text',
        name: 'OVERKILL Gaming',
        type: 'text',
        text: 'OVERKILL',
        fontFamily: 'Teko, sans-serif',
        fontSize: 72,
        fontWeight: '700',
        letterSpacing: 6,
        textTransform: 'uppercase',
        visible: true,
        locked: false,
        zIndex: 2,
        soundEffect: 'glitch',
        keyframes: [
          {
            id: 'k1',
            time: 0.8,
            x: 0,
            y: 0,
            scaleX: 2,
            scaleY: 2,
            rotation: -5,
            opacity: 0,
            fill: '#ffffff',
            stroke: '#fb7185',
            strokeWidth: 3,
            trimStart: 0,
            trimEnd: 1,
            blur: 15,
            glowColor: '#f43f5e',
            glowRadius: 30,
            easing: 'bounce',
          },
          {
            id: 'k2',
            time: 1.5,
            x: 0,
            y: 0,
            scaleX: 1,
            scaleY: 1,
            rotation: 0,
            opacity: 1,
            fill: '#ffffff',
            stroke: '#fb7185',
            strokeWidth: 1,
            trimStart: 0,
            trimEnd: 1,
            blur: 0,
            glowColor: '#f43f5e',
            glowRadius: 20,
            easing: 'easeInOut',
          },
          {
            id: 'k3',
            time: 4.2,
            x: 0,
            y: 0,
            scaleX: 1.06,
            scaleY: 1.06,
            rotation: 0,
            opacity: 1,
            fill: '#ffffff',
            stroke: '#f43f5e',
            strokeWidth: 2,
            trimStart: 0,
            trimEnd: 1,
            blur: 0,
            glowColor: '#fb7185',
            glowRadius: 25,
            easing: 'linear',
          },
          {
            id: 'k4',
            time: 4.9,
            x: 0,
            y: 0,
            scaleX: 0.1,
            scaleY: 0.1,
            rotation: 15,
            opacity: 0,
            fill: '#ffffff',
            stroke: '#fb7185',
            strokeWidth: 0,
            trimStart: 0,
            trimEnd: 1,
            blur: 10,
            easing: 'easeIn',
          },
        ],
      },
    ],
  },
  {
    id: 'vlog-creative',
    title: 'Vlog Organic Wave',
    aspectRatio: '9:16', // Vertical Shorts/TikTok format!
    fps: 60,
    duration: 5.0,
    backgroundColor: '#fffaf0',
    backgroundGradient: 'linear-gradient(180deg, #ffedd5 0%, #fef3c7 100%)',
    bgPattern: 'none',
    audioTrack: {
      id: 'chill-vlog',
      title: 'Acoustic Bright',
      duration: 5.0,
      volume: 0.8,
      syntheticType: 'chill',
    },
    transitions: [{ id: 't1', type: 'fade', time: 0, duration: 0.5 }],
    layers: [
      {
        id: 'wave-bg',
        name: 'Organic SVG Wave',
        type: 'shape',
        shapeKind: 'wave',
        visible: true,
        locked: false,
        zIndex: 1,
        soundEffect: 'whoosh',
        keyframes: [
          {
            id: 'k1',
            time: 0,
            x: 0,
            y: -150,
            scaleX: 0.8,
            scaleY: 0.8,
            rotation: -10,
            opacity: 0,
            fill: 'none',
            stroke: '#f97316',
            strokeWidth: 8,
            trimStart: 0,
            trimEnd: 0,
            blur: 0,
            glowColor: '#fdba74',
            glowRadius: 10,
            easing: 'easeInOut',
          },
          {
            id: 'k2',
            time: 1.2,
            x: 0,
            y: -100,
            scaleX: 1,
            scaleY: 1,
            rotation: 0,
            opacity: 1,
            fill: 'none',
            stroke: '#f97316',
            strokeWidth: 8,
            trimStart: 0,
            trimEnd: 1,
            blur: 0,
            glowColor: '#fdba74',
            glowRadius: 10,
            easing: 'easeInOut',
          },
          {
            id: 'k3',
            time: 4.2,
            x: 0,
            y: -80,
            scaleX: 1.05,
            scaleY: 1.05,
            rotation: 5,
            opacity: 1,
            fill: 'none',
            stroke: '#ea580c',
            strokeWidth: 8,
            trimStart: 0,
            trimEnd: 1,
            blur: 0,
            glowColor: '#fdba74',
            glowRadius: 10,
            easing: 'easeOut',
          },
          {
            id: 'k4',
            time: 5.0,
            x: 0,
            y: -50,
            scaleX: 1.2,
            scaleY: 1.2,
            rotation: 10,
            opacity: 0,
            fill: 'none',
            stroke: '#f97316',
            strokeWidth: 2,
            trimStart: 0,
            trimEnd: 1,
            blur: 10,
            easing: 'easeIn',
          },
        ],
      },
      {
        id: 'vlog-title',
        name: 'LILY VLOGS Text',
        type: 'text',
        text: 'LILY VLOGS',
        fontFamily: 'Playfair Display, serif',
        fontSize: 48,
        fontWeight: '700',
        letterSpacing: 4,
        visible: true,
        locked: false,
        zIndex: 2,
        soundEffect: 'pop',
        keyframes: [
          {
            id: 'k1',
            time: 0.6,
            x: 0,
            y: 0,
            scaleX: 0.5,
            scaleY: 0.5,
            rotation: 0,
            opacity: 0,
            fill: '#7c2d12',
            stroke: '#f97316',
            strokeWidth: 0,
            trimStart: 0,
            trimEnd: 1,
            blur: 5,
            glowColor: '#fdba74',
            glowRadius: 10,
            easing: 'elastic',
          },
          {
            id: 'k2',
            time: 1.5,
            x: 0,
            y: 0,
            scaleX: 1,
            scaleY: 1,
            rotation: 0,
            opacity: 1,
            fill: '#7c2d12',
            stroke: '#f97316',
            strokeWidth: 0,
            trimStart: 0,
            trimEnd: 1,
            blur: 0,
            glowColor: '#fdba74',
            glowRadius: 5,
            easing: 'easeInOut',
          },
          {
            id: 'k3',
            time: 4.2,
            x: 0,
            y: -10,
            scaleX: 1.05,
            scaleY: 1.05,
            rotation: 0,
            opacity: 1,
            fill: '#7c2d12',
            stroke: '#f97316',
            strokeWidth: 0,
            trimStart: 0,
            trimEnd: 1,
            blur: 0,
            glowColor: '#fdba74',
            glowRadius: 5,
            easing: 'easeOut',
          },
          {
            id: 'k4',
            time: 5.0,
            x: 0,
            y: -20,
            scaleX: 1.1,
            scaleY: 1.1,
            rotation: 0,
            opacity: 0,
            fill: '#7c2d12',
            stroke: '#f97316',
            strokeWidth: 0,
            trimStart: 0,
            trimEnd: 1,
            blur: 10,
            easing: 'easeIn',
          },
        ],
      },
    ],
  },
];
